=== CTTV/json_schema/src/bioentity/drug.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Drug",
  "description": "CTTV drug model",
  "type": "object",
  "version": "1.2",
  "properties": {
    "about": {
      "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/CTTV/json_schema/master/src/bioentity/bioentities.json"
        }
      ],
      "items": {
        "description": "An array of drug identifiers",
        "pattern": "^https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL[0-9]+$"
      }
    },
    "molecule_name": {
      "type": "string"
    },
    "molecule_type": {
      "type": "string"
    },
    "mechanism_of_action": {
      "type": "string"
    },
    "target_class": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "action_type": {
      "type": "string"
    }
  },
  "required": [
    "about"
  ],
  "additionalProperties": false
}

=== CTTV/json_schema/test/bioentities/drug.json
{
    "about": [
        "http://identifiers.org/chembl.compound/CHEMBL6"
    ],
    "molecule_name": "Indomethacin",
    "molecule_type": "Small molecule",
    "mechanism_of_action": "Cyclooxygenase inhibitor",
    "target_class": [
        "Oxidoreductase"
    ],
    "action_type": "INHIBITOR"
}
