=== CTTV/json_schema/src/literature.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Literature-based evidence strings",
  "description": "Schema for target-disease evidence extracted from the literature",
  "type": "object",
  "version": "1.2",
  "properties": {
    "type": {
      "enum": [
        "literature_evidence_string"
      ]
    },    
    "allOf": {
      "$ref": "https://raw.githubusercontent.com/CTTV/json_schema/master/src/base.json"
    },    
    "sourceID": { },
    "validated_against_schema_version": { },
    "unique_association_fields": { },
    "target" : { },
    "disease" : { },
    "evidence" : {
        "type" : "object",
        "properties" : {
            "literature" : {
                "type" : "object",
                "$ref" : "https://raw.githubusercontent.com/CTTV/json_schema/master/src/evidence/generic.json"
            }
        },
        "required" : [ "literature" ],
        "additionalProperties": false
    }
  },
  "required": [
    "type",
    "sourceID",
    "validated_against_schema_version",
    "unique_association_fields",
    "target",
    "disease",
    "evidence"
  ],
  "additionalProperties": false,  
  "import_remote_schemas": [
    { "$ref": "https://raw.githubusercontent.com/CTTV/json_schema/master/src/bioentity/base.json" },
    { "$ref": "https://raw.githubusercontent.com/CTTV/json_schema/master/src/evidence/association_score/method.json" },
    { "$ref": "https://raw.githubusercontent.com/CTTV/json_schema/master/src/evidence/association_score/probability.json" },
    { "$ref": "https://raw.githubusercontent.com/CTTV/json_schema/master/src/evidence/association_score/pvalue.json" },
    { "$ref": "https://raw.githubusercontent.com/CTTV/json_schema/master/src/evidence/association_score/rank.json" },
    { "$ref": "https://raw.githubusercontent.com/CTTV/json_schema/master/src/evidence/provenance_type/literature.json" },
    { "$ref": "https://raw.githubusercontent.com/CTTV/json_schema/master/src/evidence/provenance_type/expert.json" },
    { "$ref": "https://raw.githubusercontent.com/CTTV/json_schema/master/src/evidence/provenance_type/database.json" },
    { "$ref": "https://raw.githubusercontent.com/CTTV/json_schema/master/src/evidence/linkout/linkout.json" },
    { "$ref": "https://raw.githubusercontent.com/CTTV/json_schema/master/src/evidence/base.json" },
    { "$ref": "https://raw.githubusercontent.com/CTTV/json_schema/master/src/bioentity/disease.json" },
    { "$ref": "https://raw.githubusercontent.com/CTTV/json_schema/master/src/bioentity/target.json" }
  ]
}

=== CTTV/json_schema/examples/literature.json
{
    "type": "literature_evidence_string",
    "sourceID": "EuropePMC",
    "validated_against_schema_version": "1.2",
    "unique_association_fields": {
        "target": "http://identifiers.org/P43116",
        "publicationIDs": "http://identifiers.org/pubmed/18989535,http://identifiers.org/pubmed/18989333,http://identifiers.org/pubmed/18989444",
        "disease_uri": "http://www.ebi.ac.uk/efo/EFO_0000249"
    },
    "target": {
        "target_type": "http://identifiers.org/cttv.target/protein",
        "activity": "http://identifiers.org/cttv.activity/up_or_down",
        "id": [
            "http://identifiers.org/uniprot/P43116"
        ]
    },
    "disease": {
        "id": [
            "http://www.ebi.ac.uk/efo/EFO_0000249"
        ]
    },
    "evidence": {
        "literature": {
            "association_score": {
                "probability": {
                    "value": 0.6,
                    "method": {
                        "description": "Custom text-mining method for target-disease association"
                    }
                }
            },
            "provenance_type": {
                "literature": [
                    {
                        "id": "http://identifiers.org/pubmed/18989535",
                        "score": {
                            "rank": {
                                "position": 1,
                                "sample_size": 200,
                                "method": {
                                    "description": ""
                                }
                            }
                        },
                        "mined_sentences": [
                            "a novel proinflammatory and proamyloidogenic function for the PGE2 EP2 receptor is demonstrated in a model of familial Alzheimer's disease."
                        ]
                    }
                ]
            },
            "is_associated": true,
            "date_asserted": "2014-05-20T00:00:00Z",
            "evidence_codes": [
                "http://www.targetvalidation.org/evidence/literature_mining",
                "http://purl.obolibrary.org/obo/ECO_0000213"
            ],
            "urls": [
                {
                    "nice_name": "View article in EuropePMC",
                    "url": "http://europepmc.org/search?page=1&query=PMCID:PMC18989535&sortby=Date"
                }
            ]
        }
    }
}
