=== CTTV/json_schema/src/target_disease_association.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Target-Disease-Association",
  "description": "Schema for different types of target-disease associations used by CTTV",
  "type": "object",
  "version": "1.2",
  "properties": {
    "sourceID": {
      "type": "string",
      "description": "A source ID (database or study ID) to help identify who this data is from."
    },
    "validated_against_schema_version": {
      "description": "The CTTV-JSON schema version number against which your data was validated",
      "type": "string",
      "enum": [
        "1.1",
        "1.2"
      ]
    },
    "unique_association_fields": {
      "description": "String based key-value properties that must uniquely identify each JSON object in your data.",
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "evidence_chain": {
    "description": "A valid CTTV evidence chain schema - please choose from one of the evidence chain schemas below",
      "oneOf": [
        {
          "$ref": "https://raw.githubusercontent.com/CTTV/json_schema/master/src/evidence_chain/drug.json"
        },
        {
          "$ref": "https://raw.githubusercontent.com/CTTV/json_schema/master/src/evidence_chain/expression.json"
        },
        {
          "$ref": "https://raw.githubusercontent.com/CTTV/json_schema/master/src/evidence_chain/genetics_no_snp.json"
        },
        {
          "$ref": "https://raw.githubusercontent.com/CTTV/json_schema/master/src/evidence_chain/genetics_via_snp.json"
        },
        {
          "$ref": "https://raw.githubusercontent.com/CTTV/json_schema/master/src/evidence_chain/phenotype.json"
        }
      ]
    }
  },
  "required": [
    "sourceID",
    "validated_against_schema_version",
    "unique_association_fields",
    "evidence_chain"
  ],
  "additionalProperties": false
}

=== CTTV/json_schema/examples/generic.json
{
    "sourceID": "EuropePMC",
    "validated_against_schema_version": "1.2",
    "unique_association_fields": {
        "target": "http://identifiers.org/P43116",
        "publicationID": "http://identifiers.org/pubmed/18989535",
        "disease_uri": "http://www.ebi.ac.uk/efo/EFO_0000249"
    },
    "evidence_chain": {
        "type": "generic_evidence_chain",
        "chain": [
            {
                "target_type": "http://identifiers.org/cttv.target/protein",
                "activity": "http://identifiers.org/cttv.activity/up_or_down",
                "about": [
                    "http://identifiers.org/uniprot/P43116"
                ]
            },
            {
                "association_score": [
                    {
                        "value": 0.6,
                        "type": "probability",
                        "method": "Custom text-mining method for target-disease association"
                    }
                ],
                "provenance_type": [
                    {
                        "type": "literature",
                        "lit_refs": [
                            "http://identifiers.org/pubmed/18989535"
                        ],
                        "extracted_sentences": [
                            "a novel proinflammatory and proamyloidogenic function for the PGE2 EP2 receptor is demonstrated in a model of familial Alzheimer's disease."
                        ]
                    }
                ],
                "is_associated": true,
                "date_asserted": "2014-05-20T00:00:00Z",
                "evidence_codes": [
                    "http://www.targetvalidation.org/evidence/literature_mining",
                    "http://purl.obolibrary.org/obo/ECO_0000204"
                ],
                "preferred_hyperlink_1" : {
                	"nice_name" : "View article in EuropePMC",
                	"url" : "http://europepmc.org/search?page=1&query=PMCID:PMC18989535&sortby=Date"
                }
            },
            {
                "about": [
                    "http://www.ebi.ac.uk/efo/EFO_0000249"
                ]
            }
        ]
    }
}

=== CTTV/json_schema/examples/known_drug.json
{
    "sourceID": "ChEMBL",
    "validated_against_schema_version": "1.2",
    "unique_association_fields": {
        "chembl_targets": "http://identifiers.org/uniprot/P23219,http://identifiers.org/uniprot/P35354",
        "chembl_molecules": "http://identifiers.org/chembl.compound/CHEMBL6",
        "atc_classification": "http://identifiers.org/atc/M02AA23",
        "efo_classification": "http://purl.obolibrary.org/obo/HP_0003326"
    },
    "evidence_chain": {
        "type": "drug_evidence_chain",
        "chain": [
            {
                "target_type": "http://identifiers.org/cttv.target/protein_family",
                "target_name": "Cyclooxygenase",
                "activity": "http://identifiers.org/cttv.activity/drug_negative_modulator",
                "id": [
                    "http://identifiers.org/uniprot/P23219",
                    "http://identifiers.org/uniprot/P35354"
                ]
            },
            {
                "association_score": [
                    {
                        "value": 1,
                        "type": "probability",
                        "method": "Custom method for probability of mechanism of action association"
                    }
                ],
                "provenance_type": [
                    {
                        "type": "literature",
                        "lit_refs": [
                            "http://identifiers.org/pubmed/20301303",
                            "http://identifiers.org/pubmed/20876176"
                        ]
                    },
                    {
                        "type": "database",
                        "version": "20",
                        "id": "ChEMBL"
                    },
                    {
                        "type": "expert",
                        "status": true
                    }
                ],
                "is_associated": true,
                "date_asserted": "2014-05-20T00:00:00Z",
                "evidence_codes": [
                    "http://identifiers.org/eco/target_drug",
                    "http://purl.obolibrary.org/obo/ECO_0000205"
                ],
                "preferred_hyperlink_1": {
                    "nice_name": "ChEMBL molecule information",
                    "url": "https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL2094253"
                },
                "preferred_hyperlink_2": {
                    "nice_name": "ChEMBL target information",
                    "url": "https://www.ebi.ac.uk/chembl/target/inspect/CHEMBL6"
                }
            },
            {
                "id": [
                    "http://identifiers.org/chembl.compound/CHEMBL6"
                ],
                "molecule_name": "Indomethacin",
                "mechanism_of_action": "Small molecule",
                "target_class": [
                    "Oxidoreductase"
                ],
                "action_type": "INHIBITOR"
            },
            {
                "association_score": [
                    {
                        "value": 1,
                        "type": "probability",
                        "method": "Custom scoring method for assigning marketed drug to clinical indication"
                    }
                ],
                "provenance_type": [
                    {
                        "type": "database",
                        "version": "20",
                        "id": "ChEMBL"
                    },
                    {
                        "type": "expert",
                        "status": true
                    }
                ],
                "is_associated": true,
                "date_asserted": "2014-05-20T00:00:00Z",
                "evidence_codes": [
                    "http://identifiers.org/eco/drug_disease",
                    "http://purl.obolibrary.org/obo/ECO_0000205"
                ]
            },
            {
                "id": [
                    "http://purl.obolibrary.org/obo/HP_0003326"
                ]
            }
        ]
    }
}

=== CTTV/json_schema/test/target_disease_assoc/target_disease_association.json
{
    "sourceID": "primarysubmitterID",
    "validated_against_schema_version": "1.2",
    "unique_association_fields": {
        "chembl_targets": "http://identifiers.org/uniprot/P23219,http://identifiers.org/uniprot/P35354",
        "chembl_molecules": "http://identifiers.org/chembl.compound/CHEMBL6",
        "atc_classification": "http://identifiers.org/atc/M02AA23",
        "efo_classification": "http://purl.obolibrary.org/obo/HP_0003326"
    },
    "evidence_chain": {
        "type": "generic_evidence_chain",
        "chain": [
            {
                "about": [
                    "http://identifiers.org/ensembl/ENSG00000139618"
                ],
                "target_type": "http://identifiers.org/cttv.target/gene",
                "activity": "http://identifiers.org/cttv.activity/tolerated_by_target",
                "target_name": "optional target name"
            },
            {
                "association_score": [
                    {
                        "type": "pvalue",
                        "value": 0.0000418,
                        "method": "Moderated t-statistics computed with limma version 3.16.8. Independent filtering performed using genefilter version 1.46.1, with gene variances as filter statistic. p-values adjusted using Benjamini & Hochberg (1995) FDR correction. By default, significant differential expression called if adjusted p <= 0.05."
                    }
                ],
                "evidence_codes": [
                    "http://purl.obolibrary.org/obo/ECO_0000205"
                ],
                "provenance_type": [
                    {
                        "type": "database",
                        "version": "111111",
                        "id": "Expression_Atlas"
                    }
                ],
                "preferred_hyperlink_1": {
                    "url": "http://www.ebi.ac.uk/gxa/genes/ENSG00000127720",
                    "nice_name": "Baseline gene expression in Expression Atlas"
                },
                "preferred_hyperlink_2": {
                    "url": "http://www.ebi.ac.uk/gxa/genes/ENSG00000127720",
                    "nice_name": "Baseline gene expression in Expression Atlas"
                },
                "date_asserted": "2015-02-16T09:54:13Z",
                "is_associated": true
            },
            {
                "about": [
                    "http://www.ebi.ac.uk/efo/EFO_0000637"
                ],
                "biosamples": [
                    "breast tissue biopsy"
                ]
            }
        ]
    }
}

=== CTTV/json_schema/examples/gwas.json
{
    "sourceID": "European Variation Archive",
    "validated_against_schema_version": "1.2",
    "unique_association_fields": {
        "gene": "ENSG00000110395",
        "clinvarAccession": "http://identifiers.org/clinvar.record/RCV000038347",
        "phenotype": "http://identifiers.org/orphanet/648"
    },
    "evidence_chain": {
        "type": "genetics_via_snp_evidence_chain",
        "chain": [
            {
                "target_type": "http://identifiers.org/cttv.target/gene",
                "activity": "http://identifiers.org/cttv.activity/predicted_damaging",
                "id": [
                    "http://identifiers.org/ensembl/ENSG00000110395"
                ]
            },
            {
                "association_score": [
                    {
                        "value": 0.77,
                        "type": "probability",
                        "method": "Probability of gene-SNP assignment by mapping software"
                    }
                ],
                "provenance_type": [
                    {
                        "type": "database",
                        "version": "0.1",
                        "id": "EVA",
                        "dbxref": {
                            "version": "2014-09",
                            "url": "http://identifiers.org/clinvar/RCV000038347",
                            "id": "http://identifiers.org/clinvar"
                        }
                    },
                    {
                        "type": "expert",
                        "statement": "Primary submitter of data",
                        "status": true
                    }
                ],
                "is_associated": true,
                "date_asserted": "2014-05-20T00:00:00Z",
                "evidence_codes": [
                    "http://purl.obolibrary.org/obo/ECO_0000205",
                    "http://identifiers.org/eco/cttv_mapping_pipeline"
                ],
                "functional_consequence": "http://purl.obolibrary.org/obo/SO_0001537",
                "preferred_hyperlink_1": {
                    "nice_name": "Further details in ClinVar database",
                    "url": "http://www.ncbi.nlm.nih.gov/clinvar/RCV000038347"
                }
            },
            {
                "id": [
                    "http://identifiers.org/dbsnp/rs397517077"
                ]
            },
            {
                "association_score": [
                    {
                        "value": 0.25,
                        "type": "pvalue",
                        "method": "ClinVar star score divided by 4.0"
                    }
                ],
                "provenance_type": [
                    {
                        "type": "literature",
                        "lit_refs": [
                            "http://identifiers.org/pubmed/20301303",
                            "http://identifiers.org/pubmed/20876176"
                        ]
                    },
                    {
                        "type": "database",
                        "version": "0.1",
                        "id": "EVA",
                        "dbxref": {
                            "version": "2014-09",
                            "url": "http://identifiers.org/clinvar/RCV000038347",
                            "id": "http://identifiers.org/clinvar"
                        }
                    },
                    {
                        "type": "expert",
                        "statement": "Primary submitter of data",
                        "status": true
                    }
                ],
                "is_associated": true,
                "date_asserted": "2014-05-20T00:00:00Z",
                "evidence_codes": [
                    "http://identifiers.org/eco/GWAS",
                    "http://purl.obolibrary.org/obo/ECO_0000205"
                ]
            },
            {
                "id": [
                    "http://www.orpha.net/ORDO/Orphanet_648"
                ]
            }
        ]
    }
}
