=== CTTV/json_schema/src/evidence/generic.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "generic_evidence",
  "description": "Generic evidence linking gene/protein to disease: author-curated or computational or both",
  "type": "object",
  "version": "1.2",
  "properties": {
    "allOf": {
      "$ref": "https://raw.githubusercontent.com/CTTV/json_schema/master/src/evidence/root.json"
    },
    "association_score": {},
    "provenance_type": {},
    "is_associated": {},
    "date_asserted": {},
    "evidence_codes": {
      "type": "array",
      "description": "An array of evidence codes",
      "items": {
        "type": "string",
        "enum": [
          "http://purl.obolibrary.org/obo/ECO_0000205",
          "http://purl.obolibrary.org/obo/ECO_0000053"
        ]
      },
      "minItems": 1
    }
  },
  "patternProperties": {
    "^preferred_hyperlink_[1-9]$": {
      "$ref": "https://raw.githubusercontent.com/CTTV/json_schema/master/src/evidence/linkout.json"
    }
  },
  "required": [
    "association_score",
    "provenance_type",
    "is_associated",
    "date_asserted",
    "evidence_codes"
  ],
  "additionalProperties": false
}

=== CTTV/json_schema/test/evidence/root.json
{
    "association_score": [
        {
            "type": "pvalue",
            "value": 0.0000418,
            "method": "Moderated t-statistics computed with limma version 3.16.8. Independent filtering performed using genefilter version 1.46.1, with gene variances as filter statistic. p-values adjusted using Benjamini & Hochberg (1995) FDR correction. By default, significant differential expression called if adjusted p <= 0.05."
        }
    ],
    "evidence_codes": [
        "http://purl.obolibrary.org/obo/ECO_0000205"
    ],
    "provenance_type": [
        {
            "type": "database",
            "version": "111111",
            "id": "Expression_Atlas"
        }
    ],
    "date_asserted": "2015-02-16T09:54:13Z",
    "is_associated": true
}
